services:
  todolist.api:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: to-do-list-web-api:latest
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge