FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

COPY src/ToDoList.Api/*.csproj ./src/ToDoList.Api/
COPY src/ToDoList.Application/*.csproj ./src/ToDoList.Application/
COPY src/ToDoList.Domain/*.csproj ./src/ToDoList.Domain/
COPY src/ToDoList.Infrastructure/*.csproj ./src/ToDoList.Infrastructure/
RUN dotnet restore src/ToDoList.Api/ToDoList.Api.csproj

COPY src/ ./src

RUN dotnet publish src/ToDoList.Api/ToDoList.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

# if i want to specify port, put in two lines below
#EXPOSE 5000
#ENV ASPNETCORE_URLS=http://*:5000
# container will automatically exposes port 8080

ENTRYPOINT ["dotnet", "ToDoList.Api.dll"]